# Generated by Django 3.2 on 2021-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(),
        ),
    ]
