#Om Ghansyham Bhamare SE A 3
import numpy as np
from numpy import *
print("Arrange...")
arr1=np.arange(1,13,1)
print(arr1)
print("***********************************************")
print("1]Array Indexing")
print(arr1[3])
print("***********************************************")
print("2]Array Shape")
print(arr1.shape)
print("***********************************************")
print("3]Array Reshape")
arr2=np.arange(9).reshape(3,3)
print(arr2)
print("***********************************************")
print("4]Join Two array")
arr3=np.arange(4).reshape(2,2)
arr4=np.arange(4).reshape(2,2)
arr5=np.concatenate((arr3,arr4),axis=1)
print(arr5)
print("***********************************************")
print("5]Array Split")
arr6=np.array_split(arr1,7)
print(arr6)
print("***********************************************")
print("6]Array Search")
arr10=np.where(arr1==5)
print(arr10)
print("***********************************************")
print("7]Array Sort")
arr8=array([3,7,4,1,9,4,2,4,2,6])
arr9=np.sort(arr8)
print(arr9)